import React, { useCallback, useEffect, useState } from 'react';
import { attendanceService } from '../../services/attendanceService';

const statuses = ['present', 'absent', 'late'];
export const AttendancePage = () => {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await attendanceService.list({ page: 1, limit: 100 }); setItems(result.data || []); } catch (requestError) { setItems([]); setError(requestError?.status === 401 ? 'Session expirée.' : requestError?.status === 403 ? 'Accès refusé.' : requestError?.message || 'Impossible de charger les présences.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const update = async (item, status) => { setSaving(item.id); setError(''); try { const current = await attendanceService.getById(item.id); const saved = await attendanceService.update(item.id, { session: current.sessionId || current.session?.id || current.session?._id, learner: current.learnerId || current.learner?.id || current.learner?._id, formation: current.formationId || current.formation?.id || current.formation?._id, centre: current.centreId || current.centre?.id || current.centre?._id, status, note: current.note || '' }); setItems((previous) => previous.map((entry) => entry.id === saved.id ? saved : entry)); } catch (requestError) { setError(requestError?.status === 409 ? 'Cette présence existe déjà.' : requestError?.message || 'Impossible de modifier la présence.'); } finally { setSaving(''); } };
  if (loading) return <p className="rounded-xl bg-slate-100 p-5 text-sm text-slate-500">Chargement...</p>;
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold">Présences</h1><p className="mt-1 text-sm text-slate-500">Présences réelles de vos sessions et apprenants.</p></header>{error ? <p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error} <button type="button" onClick={load} className="ml-2 underline">Réessayer</button></p> : null}{items.length === 0 ? <p className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">Aucune présence disponible.</p> : <div className="overflow-x-auto rounded-2xl bg-white shadow-sm dark:bg-slate-800"><table className="min-w-full text-left text-sm"><thead><tr className="border-b"><th className="p-4">Apprenant</th><th className="p-4">Session</th><th className="p-4">Date</th><th className="p-4">Statut</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="p-4">{item.learnerName || 'Apprenant'}</td><td className="p-4">{item.sessionTitle || 'Session'}</td><td className="p-4">{item.sessionDate ? new Date(item.sessionDate).toLocaleDateString('fr-FR') : '—'}</td><td className="p-4"><select value={item.status} disabled={saving === item.id} onChange={(event) => update(item, event.target.value)} className="rounded-lg border p-2">{statuses.map((status) => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div>}</div>;
};
export default AttendancePage;
