import React, { useCallback, useEffect, useState } from 'react';
import { analyticsService } from '../../services/analyticsService';

const Metric = ({ label, value }) => <div className="rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-800"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value ?? 'Donnée indisponible'}</p></div>;
const first = (payload, keys) => { for (const key of keys) if (payload && payload[key] !== undefined && payload[key] !== null) return payload[key]; return null; };
export const AnalyticsPage = () => {
  const [data, setData] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [overview, growth, revenue, formations, centres] = await Promise.all([analyticsService.adminOverview(), analyticsService.adminGrowth(), analyticsService.adminRevenue(), analyticsService.adminFormations(), analyticsService.adminCentres()]); setData({ overview, growth, revenue, formations, centres }); } catch (requestError) { setData({}); setError(requestError?.status === 401 ? 'Session expirée.' : requestError?.status === 403 ? 'Accès administrateur requis.' : requestError?.message || 'Impossible de charger les analytics.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  if (loading) return <p className="rounded-xl bg-slate-100 p-5 text-sm text-slate-500">Chargement...</p>;
  if (error) return <p role="alert" className="rounded-xl bg-rose-50 p-5 text-sm text-rose-700">{error} <button type="button" onClick={load} className="ml-2 underline">Réessayer</button></p>;
  const overview = data.overview || {};
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold">Analytics plateforme</h1><p className="mt-1 text-sm text-slate-500">Indicateurs calculés par les endpoints analytics administrateur.</p></header><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Metric label="Formations" value={first(overview, ['formations'])} /><Metric label="Centres" value={first(overview, ['centres'])} /><Metric label="Apprenants actifs" value={first(overview, ['activeLearners'])} /><Metric label="Réservations" value={first(overview, ['reservations'])} /><Metric label="Revenus" value={first(overview, ['revenue'])} /></div><section className="rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-800"><h2 className="font-semibold">Formations</h2>{Array.isArray(data.formations) && data.formations.length ? <div className="mt-4 space-y-2">{data.formations.map((item) => <div key={item._id || item.id || item.title} className="flex justify-between border-b py-2 text-sm"><span>{item.title}</span><span>{item.reservationCount} réservations · {item.revenue} revenus</span></div>)}</div> : <p className="mt-3 text-sm text-slate-500">Aucune donnée disponible.</p>}</section><section className="rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-800"><h2 className="font-semibold">Évolution backend</h2>{Array.isArray(data.growth) && data.growth.length ? <pre className="mt-4 overflow-auto rounded-xl bg-slate-50 p-4 text-xs dark:bg-slate-900">{JSON.stringify(data.growth, null, 2)}</pre> : <p className="mt-3 text-sm text-slate-500">Aucune tendance disponible.</p>}</section></div>;
};
export default AnalyticsPage;
