import React, { useState } from 'react';
import { certificationsService } from '../../services/certificationsService';
import { useNotifications } from '../../context/NotificationContext';

const messageOf = (error) => error?.status === 401 ? 'Session expirée.' : error?.status === 403 ? 'Accès administrateur requis.' : error?.status === 404 ? 'Ressource introuvable.' : error?.status === 409 ? 'Cette certification existe déjà ou est déjà révoquée.' : error?.status === 400 ? 'Données invalides.' : error?.message === 'NETWORK_ERROR' ? 'Service indisponible.' : error?.message || 'Une erreur est survenue.';
export const CertificationsPage = () => {
  const { refresh } = useNotifications(); const [form, setForm] = useState({ apprenantId: '', formationId: '', centreId: '' }); const [certificate, setCertificate] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); setNotice(''); try { setCertificate(await certificationsService.create(form)); setNotice('Certification émise.'); await refresh(); } catch (requestError) { setError(messageOf(requestError)); } finally { setLoading(false); } };
  const revoke = async () => { if (!certificate || certificate.status === 'revoquee') return; setLoading(true); setError(''); try { setCertificate(await certificationsService.revoke(certificate.id)); setNotice('Certification révoquée.'); await refresh(); } catch (requestError) { setError(messageOf(requestError)); } finally { setLoading(false); } };
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold">Gestion des certifications</h1><p className="mt-1 text-sm text-slate-500">Émission et révocation via le backend. Les identifiants doivent référencer des données existantes et une réservation terminée.</p></header><section className="card p-6"><h2 className="text-lg font-semibold">Émettre une certification</h2>{error ? <p role="alert" className="mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}{notice ? <p role="status" className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p> : null}<form onSubmit={submit} className="mt-4 grid gap-3 md:grid-cols-3"><input aria-label="Apprenant" required value={form.apprenantId} onChange={(event) => setForm({ ...form, apprenantId: event.target.value })} placeholder="ID apprenant" className="rounded-lg border p-3" /><input aria-label="Formation" required value={form.formationId} onChange={(event) => setForm({ ...form, formationId: event.target.value })} placeholder="ID formation" className="rounded-lg border p-3" /><input aria-label="Centre" required value={form.centreId} onChange={(event) => setForm({ ...form, centreId: event.target.value })} placeholder="ID centre" className="rounded-lg border p-3" /><button disabled={loading} className="rounded-lg bg-brand-600 px-4 py-3 text-white disabled:opacity-50">Émettre</button></form></section>{certificate ? <section className="card p-6"><p className="text-xs uppercase text-brand-500">{certificate.certificateNumber || certificate.id}</p><p className="mt-2">Statut: {certificate.status}</p><button type="button" disabled={loading || certificate.status === 'revoquee'} onClick={revoke} className="mt-4 rounded-lg border border-rose-300 px-3 py-2 text-sm text-rose-700 disabled:opacity-50">Révoquer</button><p className="mt-4 text-sm text-slate-500">PDF et téléchargement non disponibles avec le backend actuel.</p></section> : null}</div>;
};
export default CertificationsPage;
